"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.liveMapping = {
    rtNextArchiveRecord: 'nextArchiveRecord',
    rtBaroTrend: 'barometerTrend',
    rtBaroCurr: 'barometer',
    rtOutsideTemp: 'temperature',
    rtWindSpeed: 'windSpeed',
    rtWindAvgSpeed: 'wind10minAverage',
    rtWind2mAvgSpeed: 'wind2minAverage',
    rtWindDirRose: 'windDirection',
    rtWind10mGustMaxSpeed: 'wind10minMaxSpeed',
    rtWind10mGustMaxDirRose: 'wind10minMaxDirection',
    rtOutsideHum: 'humidity',
    rtRainRate: 'rainRate',
    rtIsRaining: 'isRaining',
    rtUVLevel: 'uvLevel',
    rtSolarRad: 'solarRadiation',
    rtHeatIndex: 'heatIndex',
    rtThswIndex: 'thswIndex',
    rtRainStorm: 'stormRain',
    rtStormStartDate: 'stormStartDate',
    rt15mRain: 'rainLast15m',
    rtHourRain: 'rainLastHour',
    rtDayRain: 'rainToday',
    rtBattVoltage: 'consoleBattery',
    rtForecast: 'forecast',
    rtSunrise: 'sunrise',
    rtSunset: 'sunset'
};
exports.archiveMapping = [
    'date',
    'time',
    'temperature',
    'temperatureHigh',
    'temperatureLow',
    null,
    null,
    null,
    null,
    null,
    'humidity',
    null,
    null,
    'rainfall',
    'peakRainRate',
    'barometer',
    'forecast',
    'windSamples',
    'averageWindSpeed',
    null,
    'prevailingWindDir',
    'peakWindSpeed',
    null,
    'peakWindDirection',
    'averageSolarRadiation',
    'peakSolarRadiation',
    'averageUvIndex',
    'peakUvIndex',
    'accumulatedEt',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
];
